services:
  app:
    image: horarios-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: src.config.settings.prod
    env_file:
      - .env
    volumes:
      - db_data:/workspace/databases
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
