# Generated by Django 6.0.3 on 2026-03-04 05:13

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.TextField(unique=True)),
                ("name", models.TextField()),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="member_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("url", models.TextField()),
                ("has_selected_aulas_em_paralelo", models.BooleanField(default=False)),
                ("started_ingestion_at", models.DateTimeField(blank=True, null=True)),
                ("finished_ingestion_at", models.DateTimeField(blank=True, null=True)),
                ("failed_ingestion_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_groups",
                        to="projects.group",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
