# Generated by Django 5.0.6 on 2024-07-11 13:30

from django.db import migrations
from django.contrib.auth.hashers import make_password

def add_custom_user(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    superuser = CustomUser(
        username='admin',
        email='feupscheduler@gmail.com',
        is_staff=True,
        is_superuser=True,
        is_active=True,
        sent_email=True,
        password=make_password('passhorarios')
    )
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.RunPython(add_custom_user),
    ]