# Generated by Django 6.0.3 on 2026-03-04 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abreviation", models.TextField(unique=True)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.TextField(unique=True)),
                ("isParsed", models.BooleanField(default=False)),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("has_selected_aulas_em_paralelo", models.BooleanField(default=False)),
            ],
        ),
    ]
