# Generated by Django 3.2.12 on 2023-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ManyToManyField(blank=True, to='core.Course'),
        ),
    ]
