# Generated by Django 4.2.3 on 2024-02-18 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230427_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='courses',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='course',
            new_name='group',
        ),
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='isParsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='People', to='core.person'),
        ),
    ]
