# Generated by Django 5.0.6 on 2024-07-11 13:46

from django.db import migrations

def add_custom_person(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    Person = apps.get_model('core', 'Person')
    user = CustomUser.objects.get(email="feupscheduler@gmail.com")
    person = Person(username=user)
    person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_course_group_rename_courses_person_groups_and_more'),
        ('users', '0003_add_initial_custom_user'),
    ]

    operations = [
        migrations.RunPython(add_custom_person)
    ]
