# Generated by Django 5.0.6 on 2024-07-11 13:49

from django.db import migrations
from datetime import date

def add_project(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    Person = apps.get_model('core', 'Person')
    person = Person.objects.first()
    project = Project(
        project='Nome',
        person=person,
        data=date.today(),
        isParsed=True
    )
    project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_custom_person'),
    ]

    operations = [
        migrations.RunPython(add_project)
    ]
