# Generated by Django 6.0.2 on 2026-02-25 18:10

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("core", "0005_add_new_project"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="project",
            name="has_selected_aulas_em_paralelo",
            field=models.BooleanField(default=False),
        ),
    ]
